steps:
  - name: node:12
    entrypoint: npm
    args: [ "ci" ]
  - name: node:12
    entrypoint: npm
    args: [ "run", "lint" ]
  - name: "gcr.io/cloud-builders/gcloud"
    args: [ "app", "deploy" ]
timeout: "1600s"